export const IT = {
  Translator: "Traduttore",
  TranslatorName: "Mavisa97!",
  Language: "Lingua",
  ThisLanguage: "Italiano",
  OK: "OK",
  SteelMill: "Acciaieria",
  StainlessSteelPlant: "Impianto di acciaio inox",
  CircuitFoundry: "Fonderia di Circuiti",
  IntegratedCircuit: "Circuito integrato",
  OilWell: "Pozzo petrolifero",
  Wood: "Legna",
  LoggingCamp: "Campo di disboscamento",
  LumberMill: "Segheria",
  Lumber: "Legname",
  Paper: "Carta",
  PaperMill: "Industria cartaria",
  Book: "Libro",
  BookPublisher: "Editore di libri",
  OilRefinery: "Raffineria di petrolio",
  Sell: "Vendi",
  Upgrade: "Migliora",
  Build: "Costruisci",
  Buildings: "Edifici",
  Iron: "Ferro",
  FuelType: "Scegli il tipo di carburante",
  FuelCost: "Costo carburante",
  FuelEconomy: "Risparmio di carburante",
  FuelInStorage: "%{fuel} in magazzino",
  Plastic: "Plastica",
  Petrol: "Benzina",
  Buy: "Acquista",
  NoLiquidity: "Nessuna Liquidità",
  NoLiquidityTurnOffAutoSell:
    "Non c'è abbastanza liquidità nel mercato per %{res}, l'auto-vendita è stata disabilitata",
  Multiplier: "Moltiplicatore",
  MultiplierDesc: "Ogni 10 livelli, ottieni +1 moltiplicatore",
  SellBuilding: "Vendi edificio",
  PowerGrid: "Rete elettrica",
  TradeAmount: "Volume di scambio",
  SortBy: "Ordina per",
  SortByPrice: "Prezzo",
  SortByAmount: "Quantità",
  NotEnoughResources: "Non abbastanza risorse per questa operazione ",
  Transportation: "Trasporto",
  Cash: "Denaro",
  Aluminum: "Alluminio",
  ResearchPoint: "Punto di ricerca",
  Unlock: "Sblocca",
  BuildingUnlocked: "%{building} sono state sbloccate",
  Science: "Scienza",
  ScienceFromPowerDesc:
    "Le centrali elettriche producono una piccola quantità di Scienza quando generano energia",
  Culture: "Cultura",
  School: "Scuola",
  University: "Università",
  Polytechnic: "Politecnico",
  Colosseum: "Colosseo",
  WindTurbine: "Turbina eolica",
  Engine: "Motore",
  EngineFactory: "Fabbrica di motori",
  CameraFactory: "Fabbrica di fotocamere",
  Camera: "Fotocamera",
  Gun: "Arma",
  GunFactory: "Fabbrica di armi",
  Aircraft: "Mezzo aereo",
  AircraftFactory: "Fabbrica di mezzi aerei",
  Zeppelin: "Zeppelin",
  ZeppelinFactory: "Zeppelin Factory",
  Tank: "Carro Armato",
  TankFactory: "Fabbrica di carri armati",
  CoalPowerPlant: "Centrale elettrica a carbone",
  PetrolPowerPlant: "Centrale elettrica a petrolio",
  Copper: "Rame",
  Gas: "Gas naturale",
  GasPump: "Pompa di gas naturale",
  GasPowerPlant: "Centrale elettrica a gas",
  Missile: "Missile",
  MissileFactory: "Fabbrica di missili",
  Rocket: "Razzo",
  RocketFactory: "Fabbrica di razzi",
  BuildingPermit: "Permesso di costruzione",
  BuildingPermitDesc:
    "Hai il permesso per %{amount} edifici, hai già costruito %{amountBuilt} e ne restano disponibili %{amountLeft}",
  BuildingLocked:
    "L'edificio non è ancora disponibile, devi prima sbloccarlo nel Laboratorio di ricerca",
  MaxBuilders: "Numero massimo di edifici",
  MaxBuildersDesc: "Numero di edifici che puoi costruire contemporaneamente",
  Silicon: "Silicone",
  AluminumMine: "Miniera di alluminio",
  CopperMine: "Miniera di rame",
  SiliconMine: "Miniera di silicone",
  IronMine: "Miniera di ferro",
  CoalMine: "Miniera di carbone",
  Headquarter: "Quartier Generale",
  ResearchLab: "Laboratorio di ricerca",
  TradeCenter: "Centro di commercio",
  Resources: "Risorse",
  NotEnoughCash: "Non abbastanza Denaro",
  NotEnoughSwissMoney: "Non abbastanza Soldi svizzeri per questa operazione",
  BuildingNotEnoughFuel: "💡 Non abbastanza %{fuel}",
  AutoSell: "Auto-vendi",
  Change: "Cambia",
  StatisticsBureau: "Ufficio Statistiche",
  LogisticsDepartment: "Dipartimento Logistica",
  From: "Da",
  Top20FuelCost: "Top 20 Costi Carburante",
  To: "A",
  TransportTime: "Tempo di trasporto",
  Warehouse: "Magazzino",
  TradeWarehouse: "Magazzino per il trasporto merci",
  Coal: "Carbone",
  Video: "Video",
  ClothingFactory: "Fabbrica di vestiti",
  Clothes: "Vestiti",
  Fashion: "Moda",
  FashionFactory: "Fabbrica di moda",
  VideoFarm: "Video Farm",
  SantaFactory: "Fabbrica di Babbo Natale",
  Santa: "Babbo Natale",
  Car: "Automobile",
  CarFactory: "Fabbrica di Automobili",
  Ship: "Nave",
  SolarPanel: "Pannello Solare",
  SolarPanelDesc:
    "💡 I pannelli solari funzionano solo 5 secondi ogni 10 secondi - tutti i cicli sono allineati",
  WindTurbineDesc:
    "💡 Le turbine eoliche funzionano solo 8 secondi ogni 10 secondi - i cicli non sono allineati",
  Movie: "Cinema",
  MovieStudio: "Studio cinematografico",
  Sitcom: "Sitcom",
  TVStudio: "Studio televisivo",
  PC: "PC",
  GameStudio: "Studio di giochi",
  Game: "Gioco",
  ComputerFactory: "Fabbrica di computer",
  Shipyard: "Cantiere navale",
  PowerUsage: "Consumo di Energia",
  PowerSupply: "Alimentazione elettrica",
  Level: "Livello",
  Power: "Potenza",
  CentralBank: "Banca Centrale",
  ResourceInput: "Input - Ingresso",
  ResourceOutput: "Output - Uscita",
  ResourceStorage: "Deposito",
  ResourceChange: "Cambia",
  ResourceInOutDesc:
    "💡 Tocca sui numeri Input-Output qui sopra per evidenziare i corrispondenti Output e Input degli edifici",
  MarketUpdateIn: "Aggiornamento del Mercato tra %{time}",
  Semiconductor: "Semiconduttore",
  SemiconductorFactory: "Fabbrica di semiconduttori",
  Steel: "Acciaio",
  Bitcoin: "Bitcoin",
  BitcoinFarm: "Farm di Bitcoin",
  Dogecoin: "Dogecoin",
  DogecoinFarm: "Farm di Dogecoin",
  Guitar: "Chitarra",
  GuitarFactory: "Fabbrica di chitarre",
  Drum: "Batteria",
  DrumFactory: "Fabbrica di batterie",
  RecordingStudio: "Studio di registrazione",
  OperaHouse: "Teatro dell'Opera",
  CoalGasificationPlant: "Impianto di gassificazione del carbone",
  GasProcessingPlant: "Impianto di trattamento del Gas",
  Music: "Musica",
  Glass: "Vetro",
  PhoneFactory: "Fabbrica di telefoni",
  Phone: "Telefono",
  GlassFactory: "Fabbrica del vetro",
  Oil: "Petrolio",
  Chromium: "Cromo",
  ChromiumMine: "Miniera di Cromo",
  Uranium: "Uranio",
  EnrichedUranium: "Uranio Arricchito",
  NuclearPowerPlant: "Centrale nucleare",
  UraniumEnrichmentPlant: "Impianto di arricchimento dell'uranio",
  UraniumMine: "Miniera di Uranio",
  Titanium: "Titanio",
  TitaniumMine: "Miniera di titanio",
  TitaniumAlloyPlant: "Impianto per leghe di titanio",
  ChromiumAlloyPlant: "Impianto per leghe di cromo",
  Input: "Input",
  PanelPosition: "Posizione del pannello",
  PanelPositionDesc:
    "Mostra il pannello laterale a sinistra, a destra o in automatico (dipende dalla casella al momento selezionata)",
  InputCapacity: "Capacità di Input - Ingresso",
  Output: "Output",
  OutputCapacity: "Capacità di Output - Uscita",
  ResourceDeposit: "Deposito risorse",
  AdjacentBonus: "Bonus per l'adiacenza",
  AdjacentBonusDesc:
    "Ottieni %{bonus}% capacità extra per ogni edificio funzionante adiacente della stessa tipologia",
  ConsiderIncreaseProduction: "💡 Si consiglia di incrementrare la produzione di %{resource}",
  AlwaysTransportInput: "Modalità Accumulo",
  AlwaysTransportInputTradeCenter: "Esporta sempre",
  AlwaysTransportInputTradeCenterDesc:
    "Trasporta sempre le risorse al Centro del Commercio, anche se la vendita automatica non è abilitata per quella risorsa",
  AlwaysTransportInputDesc:
    "Trasportare sempre le risorse di input, anche se superano il requisito minimo di produzione",
  ProductionCycleLength: "Ciclo di produzione",
  ProductionCycleLengthDesc:
    "Durata di un ciclo di produzione, misurata in secondi. Allungare il ciclo aumenterà di conseguenza l'input/output per ciclo e quindi abbasserà la sua priorità nel recupero delle risorse di input",
  MaxInputDistance: "Massima distanza di Input",
  MaxInputDistanceDesc:
    "La distanza massima da cui questo edificio può recuperare risorse di input, misurata in numero di caselle",
  AutoSellCapacity: "Capacità della vendita automatica",
  AutoSellCapacityDesc:
    "Quantità massima di risorse che la vendita automatica può gestire al secondo, per risorsa",
  CurrentAutoSellCapacityMultiplier: "Moltiplicatore attuale: x%{n}",
  AutoSellConcurrency: "Concorrenza di vendita automatica",
  AutoSellConcurrencyDesc:
    "Numero massimo di risorse che la vendita automatica può gestire contemporaneamente",
  MaxAutoSellConcurrencyReached:
    "Hai raggiunto la concorrenza di vendita automatica massima, disattiva un'altra vendita automatica per abilitare questa",
  WallStreet: "Wall Street",
  MarketCap: "Capitalizzazione di mercato",
  MarketCapDesc:
    "Capitalizzazione di mercato totale (ossia, valore di mercato) della tua azienda",
  BuildingValuation: "Valutazione degli edifici",
  BuildingValuationDesc:
    "Valore totale dei tuoi edifici, inclusi permessi di costruzione e miglioramenti",
  ResourcesValuation: "Valutazione delle risorse",
  ResourcesValuationDesc: "Valore totale delle risorse nel tuo inventario",
  Battery: "Batteria",
  BatteryFactory: "fabbrica di batterie",
  RatingBuy: "Buy",
  RatingSell: "Sell",
  SwissShop: "Negozio svizzero",
  RatingHold: "Hold",
  RatingOutperform: "Outperform",
  RatingUnderperform: "Underperform",
  StockRating: "Stock Rating",
  JetEngine: "Motore a reazione",
  Helicopter: "Elicottero",
  Lithium: "Litio",
  LithiumMine: "Miniera di litio",
  LiionBatteryFactory: "Fabbrica di batterie agli ioni di litio",
  HelicopterFactory: "Fabbrica di elicotteri",
  Satellite: "Satellite",
  ToyFactory: "Fabbrica di giocattoli",
  Toy: "Giocattolo",
  SpaceStation: "Stazione spaziale",
  SpaceStationFactory: "Fabbrica di stazioni spaziali",
  OperatingSystem: "Sistema operativo",
  OperatingSystemCompany: "Sistema operativo Inc",
  LinuxDistribution: "Distribuzione Linux",
  Internet: "Internet",
  WebBrowser: "Web Browser",
  Console: "Console",
  ConsoleFactory: "Fabbrica di console",
  Train: "Treno",
  TrainFactory: "Fabbrica di treni",
  ShoeFactory: "Fabbrica di scarpe",
  Shoes: "Scarpe",
  ArtilleryFactory: "Fabbrica di artiglieria",
  Artillery: "Artiglieria",
  SubmarineFactory: "Fabbrica di sottomarini",
  Submarine: "Sottomarino",
  Spaceship: "Astronave",
  RobotFactory: "Fabbrica di robot",
  Robot: "Robot",
  SpaceshipFactory: "Fabbrica di astronavi",
  SatelliteFactory: "Fabbrica di satelliti",
  JetEngineFactory: "Fabbrica di motori a reazione",
  StockRatingDesc:
    "Consenso sul rating azionario degli analisti di Wall Street, che influisce sulla capitalizzazione di mercato e viene aggiornato con il mercato",
  OfflineEarning: "Guadagni offline",
  PerMin: "%{amount}/minuto",
  OfflineEarningTime: "Tempo di guadagno massimo offline",
  OfflineEarningTimeDesc:
    "Guadagnerai offline fino a questa soglia",
  BuyPermit: "Acquista permesso",
  Settings: "Impostazioni",
  Sound: "Effetti sonori",
  SoundDesc: "Attiva gli effetti sonori come clic o suono di errore",
  AutoHighlight: "Auto evidenziazione",
  AutoHighlightDesc:
    "Evidenzia automaticamente edifici dello stesso tipo quando selezioni un edificio",
  MusicDesc:
    "Accendi la musica: It's Not Over 'Til The Bossa Nova di Shane Ivers (https://www.silvermansound.com)",
  Credits: "Crediti",
  Icons: "Icone",
  MisplacedBuilding:
    "⛔ Questo/a %{building} non è posizionato sul deposito di risorsa corretto.",
  HighlightBuildings: "Evidenzia edifici",
  HighlightTurnedOff: "...che sono spenti",
  HighlightStockpileModeOn: "...che hanno la 'modalità accumulo' abilitata",
  HighlightProductionCycleNotDefault: "...che hanno il ciclo di produzione > 1",
  HighlightMaxInputDistanceNotDefault: "...che hanno la distanza massima di input < ∞",
  HighlightNotMakingProfit: "...non creano profitto",
  NBuildingsAreHighlighted: "%{n} building(s) sono evidenziati",
  TurnOffProduction: "Spegni",
  TurnOffProductionDesc:
    "Disattiva la produzione dell'edificio. L'edificio non trasporterà più risorse e non utilizzerà energia",
  ApplyToAll: "Applica a tutti gli %{building}",
  FuelCostNumber: "%{cost} %{fuel}",
  Unlimited: "Illimitato",
  Transport: "Trasporto",
  TileModifier: "Modificatore casella",
  ShowAllModifiers: "Mostra tutti i modificatori",
  HideAllModifiers: "Nascondi tutti i modificatori",
  NumberOfBuildings: "Numero di edifici che possiedi",
  ShowContent: "Mostra contenuto",
  HideContent: "Nascondi contenuto",
  BuyExpansionPack: "Acquista per %{price}",
  Cities: "Città",
  InputStrategy: "Strategia di input",
  InputStrategyClose: "Più vicino",
  InputStrategyCloseDesc:
    "Preferisci il magazzino più vicino con risorse sufficienti",
  InputStrategyFar: "Più distante",
  InputStrategyFarDesc:
    "Preferisci il magazzino più lontano con risorse sufficienti",
  InputStrategyAmount: "Quantità",
  InputStrategyAmountDesc:
    "Preferisci il magazzino con la maggior quantità di risorse, indipendentemente dalla distanza",
  FuelCostSave: "Risparmio nel costo del carburante",
  FuelCostSaveDescV2:
    "I magazzini risparmiano una certa percentuale di carburante per il trasporto delle risorse rispetto ad altri edifici, maggiore è il livello, maggiore sarà il risparmio",
  SoftwareCompany: "Compagnia di software",
  Software: "Software",
  ScreenFactory: "Fabbrica di schermi",
  Screen: "Schermo",
  JoinDiscord:
    "Unisciti al nostro server Discord per gli ultimi aggiornamenti, suggerimenti e discussioni",
  ClaimOfflineEarning: "Riscuoti guadagni offline",
  OfflineTime: "Tempo offline",
  Minutes: "%{time}minuti",
  MaxUpgrade: "Miglioramento massimo",
  MaxUpgradeDesc: "Hai raggiunto il massimo miglioramento",
  ClaimAmount: "Denaro +%{amount}",
  EffectiveTime: "Tempo effettivo",
  EffectiveTimeDesc:
    "Il tuo tempo effettivo di guadagno offline è limitato %{time}minuti.",
  BuildSearchPlaceholder: "Digita l'edificio o la risorsa da cercare",
  MineOverlayWarning: "%{building} non è influenzato dal modificatore di casella",
  WholesaleCenter: "Centro Ingrosso",
  OrderFrom: "Ordina da %{name}",
  ExpireIn: "Scade tra",
  Reward: "Ricompensa",
  PerSecond: "%{time}/s",
  PolicyPoint: "Punto politica",
  PolicyPointDesc: "💡 Più politiche sono attive, maggiore è il costo per ciascuna politica",
  NextOrderIn: "Prossimo ordine tra",
  FillOrder: "Riempi l'ordine",
  RejectOrder: "Rifiuta/Passa",
  WholesaleCenterLocked:
    "Hai bisogno di almeno %{required} risorse diverse per sbloccare il Centro all'ingrosso. Hai solo %{current} risorse",
  OrderFilled: "L'ordine per %{from} è stato riempito con successo!",
  PolicyCenter: "Centro Politica",
  NewOrder:
    "È arrivato un nuovo ordine da%{from} per favore controlla nel Centro Ingrosso",
  Policies: "Politiche",
  PolicyNotEnoughTime: "Non hai abbastanza punti politica per questa politica",
  WholesaleCenterOrderFasterDesc:
    "Il Centro Ingrosso riceve gli ordini 2 volte più velocemente e la dimensione dell'ordine è 2 volte più grande",
  PolicyOilWellPowerx2: "Sovralimentazione pozzi petroliferi",
  PolicyOilWellPowerx2Desc: "I pozzi petroliferi producono il doppio del petrolio e utilizzano il doppio dell'energia",
  HalfTransportSpeed: "Rallenta per risparmiare",
  HalfTransportSpeedDesc:
    "La velocità di trasporto è rallentata del 25% e il costo del carburante è ridotto del 25%",
  RefineryMoreOil: "Mo Benzina Mo Problemi",
  RefineryMoreOilDesc:
    "Le raffinerie di petrolio producono il 50% in più di benzina e il 50% in meno di plastica",
  RefineryMorePlastic: "Mo Plastiche Mo Problemi",
  RefineryMorePlasticDesc:
    "Le raffinerie di petrolio producono il 50% in meno di benzina e il 50% in più di plastica",
  FreeOilTransportDesc:
    "Il trasporto di Petrolio non costa carburante, ma i pozzi petroliferi utilizzano il doppio dell'energia",
  SuperSteelMill: "Cuore di ferro",
  SuperSteelMillDesc:
    "Le acciaierie utilizzano il 50% in meno di carbone, il 25% in più di ferro e il 25% in più di energia",
  AlSemiconductor: "Al Circuit",
  AlSemiconductorDesc: "Le fonderie di circuiti utilizzano l'alluminio invece del rame",
  CostSaver: "Risparmio dei costi",
  CostSaverDesc:
    "Se l'input di un edificio costa più del suo output, interrompi la produzione",
  CostSaverBuildingDesc:
    "La politica di risparmio sui costi è attiva, la produzione si accenderà/spegnerà automaticamente in base alla sua redditività",
  CostSaverBuildingWarning:
    "La politica di risparmio sui costi è attiva, non è possibile modificare manualmente la produzione",
  GlassUseCoal: "Vetro nero",
  GlassUseCoalDesc: "Le fabbriche del vetro utilizzano il 50% in più di carbone e il 50% in meno di silicio",
  AdjacentBonusOnlyOutput: "Bonus Adiacenza +",
  AdjacentBonusOnlyOutputDesc:
    "Il bonus adiacenza non richiede più input ma utilizza più potenza ed è efficace solo per il 50%.",
  IronMine2xOutput: "Ferro pesante",
  IronMine2xOutputDesc:
    "Le miniere di ferro producono il doppio del ferro, ma il trasporto del ferro costa il doppio del carburante",
  SolarPanelAlwaysWork: "Il sole non tramonta mai",
  SolarPanelAlwaysWorkDesc:
    "Il pannello solare funziona il 100% delle volte ma produce il 60% di energia in meno",
  SteelScience: "Conoscenza attraverso l'acciaio",
  SteelScienceDesc: "Le acciaierie utilizzano input 2x e producono scienza extra",
  ShoppingSpree: "Shopping sfrenato",
  ShoppingSpreeDesc:
    "Se la capacità di output di una risorsa è insufficiente, acquista automaticamente l'importo della scarsità dal Centro di Scambio (se la risorsa ha una vendita automatica, verrà ignorata)",
  ShoppingSpreeTradeCenterDesc:
    "💡 La politica di Shopping Spree è attiva, Il Centro di Scambio acquisterà automaticamente le risorse in scarsità",
  ExtraPolicyPoints: "Lobbista politico",
  CrAlloyUseFe: "Cromerro",
  CrAlloyUseFeDesc:
    "Gli impianti per leghe di cromo non utilizzano il litio ma utilizzano invece il doppio del ferro",
  DoubleTileModifier: "Il potere della natura",
  TileModifierOutputOnly: "Modificatore della casella +",
  GasPlantPetrol: "Liquidatore di Gas",
  GasPlantPetrolDesc: "Le centrali a gas utilizzano gas extra per produrre benzina",
  CoalPlantFuel: "Liquidatore di carbone",
  CoalPlantFuelDesc: "Le centrali a carbone utilizzano carbone extra per produrre benzina",
  Welcome: "Benvenuto",
  SeeTutorialAgain: "Rifai il tutorial",
  HelpTranslateTheGame: "Aiuta a tradurre il gioco🌐",
  NextTutorial: "Prossimo",
  Tutorial1:
    "Industry Idle è im gioco di <em>gestione delle risorse</em> dove costruisci fabbriche 🏭, produci beni 📦 e ottini profitti💸.<br><br>Addentriamoci nei concetti di base per iniziare. - non ci vorrà molto, è una promessa 😉.",
  Tutorial2:
    "Tutti gli edifici richiedono energia⚡, hai <em>turbine eoliche</em> che generano energia. Puoi vedere lo stato della tua alimentatazione attuale, sul lato sinistro della barra superiore.<br><br>Potresti aver notato che le turbine eoliche funzionano solo l'<em>80%</em> del tempo. Puoi prendere in considerazione la costruzione di altri tipi di centrali elettriche così da generare dell'energia stabile.",
  Tutorial3:
    "You have a lot of <em>resource deposits</em> on the map. To extract resources, you have to build mines⛏️ <em>on top of</em> the corresponding deposit.<br><br>For example, you have an <em>oil well🛢️</em> that extracts <em>oil</em> from an oil deposit.<br></br>Resource deposits are unlimited - no need to worry about them running out. Apart from mines, other buildings can be built on any empty tile.",
  Tutorial5:
    "To make money, you need to export your resources via the trade center. To do this, simply turn on <em>auto sell</em> for that resource.<br></br>You can also buy resources from the trade center as well. Remember <em>if you buy a resource, you will drive up the price</em> and if you sell a resource, you will drive down the price.<br><br>The market is <em>volatile</em> and the price📈 changes regularly.",
  Tutorial6:
    "To build new buildings, you need to unlock it first in the <em>research lab🧪</em>. The research lab also converts science to research points.<br><br>Your wind turbine (and other power plants) produces a small amount of science when running. And you can build school🏫 and other dedicated buildings to boost science later.<br><br>Now you have learned all the basics, start to build up your economy! Here are some <em>cash💸</em> and <em>petrol⛽</em> to give you a jump start.",
  WelcomePlay: "Play",
  WelcomePlayMuted: "Play (🔇Music)",
  Chat: "Chat",
  RestoreFromBackup: "Restore from Backup",
  RestoreFromBackupFail:
    "Failed to restore backup from Steam Cloud: are you sure there's a backup?",
  RestoreFromBackupTitle: "Are you sure?",
  RestoreFromBackupDesc:
    "You normally don't need to restore from cloud backup, unless your local save is lost. Cloud backup are a bit older than your local save",
  ChangeName: "Change",
  SaveName: "Save",
  NameValidationRule:
    "Your name should only contain letters and numbers and be between 5-15 chars",
  NameValidationRuleProfanity: "Your name should not contain profanity",
  ChatMessageRateLimit: "You can only send a new chat message every 10 seconds",
  NameSaved: "Your name has been changed successfully",
  NoMessages: "No new messages",
  Leaderboard: "Leaderboard",
  Name: "Name",
  Tips1:
    "Stock ratings have 5 levels: Buy, Overperform, Hold, Underperform and Sell",
  Tips2:
    "Buildings will stop transporting resources if there's already enough for production, unless you turn on stockpile mode",
  Tips3:
    "Fuel cost for resource transportation is determined by distance and amount of resources",
  Tips4:
    "Buildings will only transport a resource if the amount found on map exceeds the input capacity",
  Tips5:
    "Buildings will only transport a resource from Trade Center if auto sell is turned off for that resource",
  Tips6:
    "You can see the fuel cost for a resource under the corresponding input capacity section",
  Tips7:
    "If you buy a resource, you will drive up the price. If you sell a resource, you will drive down the price",
  Tips8:
    "You can see the chart for each resource's amount and its change over time in Statistics Bureau",
  Tips9:
    "Research points needed for a building is determined by the market price of it's input resources",
  Tips10:
    "Different resources are priced differently in market - always be prepared for market volatility",
  Tips11:
    "It's a good idea to always check your power and fuel supply before expanding your production",
  FPS30: "Energy Saving",
  OfflineModeDesc:
    "Cannot connect to the server: offline earnings will not be generated. Please check your internet connection",
  OptOut: "Opt Out",
  OptIn: "Reset and Enable",
  LeaderboardOptOut: "Leaderboard Opt-Out",
  LeaderboardOptIn: "Reset and Enable Leaderboard",
  LeaderboardOptInDesc:
    "Your data needs to be RESET before you can re-enable leaderboard, are you sure?",
  RewardAdsFailed: "Reward video did not complete",
  OfflineEarningDoubleSuccess: "You have doubled your offline earning",
  FPS30Desc:
    "Turn on energy saving mode will run the game at 30FPS instead of 60FPS. This will make your battery last longer",
  HighlightAll: 'Highlight "%{type}"',
  HighlightInput: "🔍 Highlight %{type} Input",
  HighlightOutput: "🔍 Highlight %{type} Output",
  RunOutIn: "Out in %{time}",
  SwissBank: "Swiss Bank",
  SwissMoney: "%{money} 💵",
  PrestigeDesc: "If you start in a new city, you will get %{money} 💵",
  RestorePurchases: "Restore Purchases",
  RestorePurchasesSuccess: "Your purchases have been restored",
  RestorePurchasesFailed: "Your purchases did not restore",
  ExpansionPacks: "Expansion Packs",
  ExpansionPack1: "Expansion Pack 1",
  RequireExpansionPack1: "Expansion Pack 1",
  RequireExpansionPack1Desc: "This is only available for Expansion Pack 1",
  RequireAnyExpansionPack: "Expansion Packs Exclusive",
  RequireAnyExpansionPackDesc:
    "This feature requires you to own at least one of the expansion packs",
  HideRewardAd: "Hide Rewarded Ads",
  HideRewardAdDesc:
    "All in-game ads are optional rewarded ads. This will hide all the rewarded ad options from game.",
  HideDiscordBanner: "Hide Discord Banner",
  HideDiscordBannerDesc:
    "Hide Discord and storefront banner in the headquarter",
  HideChat: "Hide Chat Message",
  PurchaseFailed: "The purchase did not complete",
  PurchaseSteamContinue: "Please finish your purchase on Steam",
  PurchaseSuccess: "The purchase has completed, thanks for your support",
  PrestigeCurrency: "Swiss Money 💵",
  RestartDesc:
    "💡 Just want to restart? You can tap on Start In A New City above and choose your current city",
  PrestigeGoBack: "Go Back",
  ProductionMultiplier: "Production Multiplier",
  ProductionMultiplierDesc:
    "A boost to all your buildings' production capacity (including mines, factories, power plants, science and culture buildings)",
  FuelCostDiscount: "Fuel Cost Discount",
  FuelCostDiscountDesc:
    "Gives a discount to fuel cost when transporting resources",
  AutoSellCapacityMultiplier: "Auto Sell Capacity Multiplier",
  AutoSellCapacityMultiplierDesc:
    "A multiplier that is applied to your auto sell capacity reagardless of the current capacity",
  BuildingPermitCostDivider: "Building Permit Cost Divider",
  BuildingPermitCostDividerDesc: "Divide building permit cost by this divider",
  ExtraAdjacentBonus: "Extra Adjacent Bonus",
  ExtraAdjacentBonusDesc:
    "Extra bonus capacity for every adjacent working building of the same type",
  PrestigeAlertTitle: "Are you sure?",
  PrestigeAlertContent:
    "Your company will be liquidated. You will cash in %{amount} Swiss money and start a new company in %{city}",
  PrestigeCurrencyDesc:
    "This is the money in your secret Swiss bank account, you can carry it with you when you start in a new city",
  Prestige: "Cash In",
  Cancel: "Cancel",
  SaveFileCorrupted: "Save File Corrupted",
  LoadGameError: "Failed to Load Game",
  LoadGameErrorMessage: "Error message: %{message}",
  LoadGameErrorDesc:
    "Please check your Internet connection. If the problem persists, please contact support",
  ExpansionPackIncompatible:
    "You are importing a save with expansion packs but your game doesn't have the required expansion packs",
  CashIn: "Cash In",
  CurrentCity: "Current City",
  CashInDesc:
    "Your will get this amount to your Swiss bank account if you start in a new city. It is based on your company's market cap and it must reach %{amount} before you can earn Swiss money",
  CitySize: "Map Size",
  GridType: "Grid Type",
  StartInThisCity: "Start In %{city}",
  CityBonus: "City Bonus",
  ResourceTilePercentage: "Resource Tiles",
  MapSquareGrid: "Square",
  MapHexGrid: "Hex",
  Stockholm: "Stockholm",
  Rotterdam: "Rotterdam",
  Oslo: "Oslo",
  StPetersburg: "St. Petersburg",
  Hamburg: "Hamburg",
  HamburgBonus:
    "<li>Zeppelin factories are unlocked</li><li>Semiconductor factories have 2x productivity</li><li>Shipyards have 2x capacity</li><li>Car factories have 2x capacity</li><li>Li-ion battery factories are unlocked</li>",
  Toulouse: "Toulouse",
  Rome: "Rome",
  RomeBonus:
    "<li>Colosseums are unlocked</li><li>Colosseums have 2x productivity</li><li>Start with level 5 policy center</li><li>Opera houses have 2x capacity</li><li>Recording studios also produce culture</li>",
  Detroit: "Detroit",
  Boston: "Boston",
  BostonBonus:
    "<li>Start with level 5 research lab</li><li>Polytechnics are unlocked</li><li>Polytechnics have 2x capacity</li><li>Schools have 2x capacity</li><li>University have 2x productivity</li>",
  HideNotProducing: "Hide resources that are not being produced",
  SortByStorage: "Storage",
  SortByName: "Name",
  PlayerTrade: "Player Trade",
  AddTradeFail: "Failed to add your trade",
  AddTradeExceedMaximumTrade:
    "You can only have maximum %{number} active trades, please claim or cancel one of them first",
  AddTradeSuccess: "Your trade has been added successfully",
  ClaimTradeFail: "Failed to claim this trade, please try again later",
  CancelTradeSuccess: "Your trade has been cancelled successfully",
  CancelTradeFail: "Failed to cancel this trade, please try again later",
  AcceptTradeFail: "Failed to accept this trade, please try again later",
  PlayerTradeBanner: "Trade Resources with Other Players",
  PlayerTradeResource: "Resource",
  PlayerTradeAmount: "Amount",
  PlayerTradePrice: "Price $",
  PlayerTradeValue: "Value $",
  PlayerTradeWaiting: "Waiting...",
  AddTrade: "Add Trade",
  AcceptTrade: "Accept",
  CancelTrade: "Cancel",
  ClaimTrade: "Claim",
  PasteYourSave: "Please paste your save data",
  FailedToImportSave: "Failed to Import Save",
  FailedToImportSaveDesc:
    "Your save file is incompatible or corrupted: %{error}",
  SaveCopiedToClipboard: "Your save data has been copied to your clipboard",
  CancelActiveTradeFirst:
    "You have active player trades, please cancel/claim them first",
  PlayerTradeQuotaExceed: "This trade has exceeded your quota",
  PlayerTradeValidRange: "Range: %{min} ~ %{max}",
  PlayerTradeQuota: "Quota Left: %{value}",
  PlayerTradeUnavailable:
    "You need to have at least one resource in production and in storage before you can trade with players",
  PlayerTradeToClaim: "Your have %{num} new trade(s) to claim in Player Trade",
  PowerBank: "Power Bank",
  PowerBankBuildDesc:
    "Store surplus power and provide power supply during shortage",
  WarehouseBuildDesc: "Warehouses can transport and store any resources",
  PowerBankChargeSpeed: "Charge Speed",
  PowerBankPowerLeft: "Power Left",
  PowerBankMoreCapacity: "Battery Saver",
  PowerBankMoreCapacityDesc:
    "Power banks charge at 50% speed but have 50% more capacity",
  PowerBankNotWorking: "⛔ Power banks only work next to a power plant",
  ColorTheme: "Color Theme",
  ColorThemeDesc:
    "Color theme for game icons, highlight, grid and background. REQUIRES RELOAD",
  SiliconMine2xOutput: "Silicon Valley",
  SiliconMine2xOutputDesc:
    "Silicon mines produce 2x silicon but use 50% more power and silicon transport costs 50% more fuel",
  CoalMine2xOutput: "Industrial Revolution",
  CoalMine2xOutputDesc:
    "Coal mines produce 2x coal but use 50% more power and coal transport costs 50% more fuel",
  AlMine2xOutput: "Aluminum Smelting",
  AlMine2xOutputDesc:
    "Aluminum mines produce 2x aluminum and use 2x more power",
  LoggingCamp2xOutput: "Deforestation",
  LoggingCamp2xOutputDesc:
    "Logging camps produce 2x wood and wood transport costs 2x fuel",
  PowerBankLeft: "Power Bank",
  ColorThemeEditor: "Color Theme Editor",
  ColorThemeEditorDesc:
    "You can override colors in the current color theme. You currently have %{num} overrides",
  ColorThemeEditorSave: "Save",
  ColorThemeEditorReset: "Reset",
  ColorThemeEditorResetAll: "Reset All",
  NewMessageMentions: "A new message mentions you: %{message}",
  HideChatMentions: "Hide Chat Mentions",
  HideChatMentionsDesc:
    "Hide the audio and toast notification when a chat message mentions me,",
  AcceptTradeFailRateLimit:
    "You can only accept one trade every %{time} seconds",
  DowngradeBuilding: "Downgrade",
  WarehouseInputRoutes: "Input Routes",
  WarehouseAddInput: "Add Route",
  WarehouseTapToSelect: "Tap on Map to Select...",
  WarehouseFindOnMap: "🔍 Find on Map",
  WarehouseRemoveRoute: "Remove",
  WarehouseAddRouteFail:
    "Failed to add route: selected tile is not valid source",
  LevelN: "Level %{level}",
  Surplus: "Surplus",
  Production: "Production",
  Consumption: "Consumption",
  WarehouseInputCapacityDescV2:
    "Total capacity of inward transportation, divided equally among all routes",
  PlayerCountryFlag: "Player Flag",
  PlayerCountryChooseFlag: "In Alphabetical Order of Country Code",
  WindTurbineAlwaysWork: "The Wind Rises",
  WindTurbineAlwaysWorkDesc:
    "Wind turbines work 100% of the time but produces 30% less power",
  BookPublisherScience: "Science Literature",
  BookPublisherScienceDesc:
    "Book publishers produce science instead of culture",
  BatteryFuelEconomy: "Rechargeable Battery",
  BatteryFuelEconomyDesc:
    "Battery fuel economy improves by 100% (ie. 50% fuel cost)",
  ShowTheoreticalInputOutputCapacity: "Show theoretical input/output capacity",
  SpecialTransportCost: "Resources with Special Transport Cost",
  FreeTransportCost: "Resources with Free Transport Cost",
  Osaka: "Osaka",
  OsakaBonus:
    "<li>Resources tend to spawn in clusters</li><li>Warehouse provide 50% more fuel save</li><li>Unique building: manga publisher</li><li>Unique building: anime studio</li><li>Semiconductor factories have 2x productivity</li><li>Li-ion battery factories have 2x capacity</li><li>Battery factories are unlocked</li><li>Battery factories have 2x capacity</li><li>Battery fuel economy improves by 100%</li><li>Battery factories do not require coal</li><li>Start with 100K batteries</li>",
  HideChatDescV2:
    "Hide chat message from the bottom toolbar. By showing chat messages, you agree to our ",
  HideChatDescV2ToS: "Terms of Service",
  IntegratedCircuitFab: "Integrated Circuit Fab",
  MangaPublisher: "Manga Publisher",
  Manga: "Manga",
  AnimeStudio: "Anime Studio",
  Anime: "Anime",
  PlayerTradeAction: "Action",
  PlayerTradeBuy: "Buy",
  PlayerTradeSell: "Sell",
  PlayerTradeBid: "Bid",
  PlayerTradeAsk: "Ask",
  ClaimTradeSuccessV2:
    "Your trade has been claimed successfully: %{cashOrResource}",
  AcceptTradeSuccessV2:
    "This trade has been accepted by you: %{cashOrResource}",
  ResourceExplorer: "Resource Explorer",
  ResourceExplorerDesc: "Allow you to extract resources from an empty map tile",
  ResourceExplorerDescLong:
    "💡 Resource Explorers do not have adjacent bonus. The power usage differs per resource",
  ResourceExplorerSelectResource: "Explore",
  ProductionSettings: "Production Settings",
  PlayerTradePartialFillTitle: "Choose Fill Percentage",
  PlayerTradeAmountNotValidV2: "Minimum trade amount allowed is 1",
  PlayerTradeOptOut:
    "You have opted out of the leaderboard, you cannot trade with other players",
  FirstTimeReadGuide:
    "💡 Need a little bit of help on how to play? Tap to read the beginner's guide!",
  ReadSteamGuideV2: "Game Guides",
  ReadSteamGuideV2Desc:
    "You can read community created guides on Steam - and you can create your own as well",
  ChatMessageTooLong: "Your chat message exceeded the maximum chars allowed",
  ChatPlaceholderV2: "Type your message: max %{length} chars",
  ProfitBreakdownOutput: "%{res} Output",
  ProfitBreakdownInput: "%{res} Input",
  ProfitBreakdownFuel: "Fuel Cost",
  BuildingProfit: "Profit",
  RestoreBackup: "Restore",
  SteamLogin: "Sign In Through Steam",
  SteamLoginDialogDesc:
    "Your local save has Expansion Pack enabled, you need to sign in through Steam to continue. Or you can ERASE YOUR LOCAL SAVE and start over",
  SteamLoginDesc:
    "If you own expansion packs on Steam, you can play with expansion packs on web after signing in",
  SteamLoginYes: "Sign In",
  SteamLoginNo: "Erase & Start Over",
  KungFuDojo: "Kung-Fu Dojo",
  KungFu: "Kung-Fu",
  TaiChi: "Tai-Chi",
  TaiChiDojo: "Tai-Chi Dojo",
  HongKong: "Hong Kong",
  FreeTransportToTradeCenter: "International Export Trade",
  FreeTransportToTradeCenterDesc:
    "Transportation to the trade center does not cost fuel but transportation from the trade center cost 50% more fuel",
  TaiChi10xCulture: "Pearl of the Orient",
  PlayerTradeYouHave: "In Storage: %{amount}",
  PlayerTradeFillValue: "Value",
  FiberFactory: "Fiber Factory",
  Fiber: "Fiber",
  Achievements: "Achievements",
  AchievementsDesc: "You have achieved %{number} out of %{total} achievements",
  AchievementsReward: "Reward: Swiss Money +%{swiss}",
  AchievementsRewardToast:
    "You have claimed the reward:  Swiss Money +%{swiss}",
  AchievementsClaim: "Claim",
  AchievementsToast:
    "You have achieved %{name}, claim your reward in Headquarter",
  AchievementStockholm100: "Freshman Viking",
  AchievementStockholm100Desc:
    "Earn 100 Swiss Money in Stockholm in a single run",
  AchievementStockholm500: "Graduate Viking",
  AchievementStockholm500Desc:
    "Earn 500 Swiss Money in Stockholm in a single run",
  AchievementStockholm1000: "Experienced Viking",
  AchievementStockholm1000Desc:
    "Earn 1000 Swiss Money in Stockholm in a single run",
  AchievementOslo100: "Norwegian Oil Hobbyist",
  AchievementOslo100Desc: "Earn 100 Swiss Money in Oslo in a single run",
  AchievementOslo500: "Norwegian Oil Enthusiast",
  AchievementOslo500Desc: "Earn 500 Swiss Money in Oslo in a single run",
  AchievementOslo1000: "Norwegian Oil Tycoon",
  AchievementOslo1000Desc: "Earn 1000 Swiss Money in Oslo in a single run",
  AchievementRotterdam100: "Pinwheel Owner",
  AchievementRotterdam100Desc:
    "Earn 100 Swiss Money in Rotterdam in a single run",
  AchievementRotterdam500: "Wind Mill Owner",
  AchievementRotterdam500Desc:
    "Earn 500 Swiss Money in Rotterdam in a single run",
  AchievementRotterdam1000: "Wind Turbine Owner",
  AchievementRotterdam1000Desc:
    "Earn 1000 Swiss Money in Rotterdam in a single run",
  AchievementDetroit100: "Local Car Dealer",
  AchievementDetroit100Desc: "Earn 100 Swiss Money in Detroit in a single run",
  AchievementDetroit500: "Regional Car Distributor",
  AchievementDetroit500Desc: "Earn 500 Swiss Money in Detroit in a single run",
  AchievementDetroit1000: "National Car Monopoly",
  AchievementDetroit1000Desc:
    "Earn 1000 Swiss Money in Detroit in a single run",
  AchievementBoston100: "Bachelor of Earning Money",
  AchievementBoston100Desc: "Earn 100 Swiss Money in Boston in a single run",
  AchievementBoston500: "Master of Gaining Money",
  AchievementBoston500Desc: "Earn 500 Swiss Money in Boston in a single run",
  AchievementBoston1000: "Ph.D in Printing Money",
  AchievementBoston1000Desc: "Earn 1000 Swiss Money in Boston in a single run",
  AchievementRome100: "Diocletian",
  AchievementRome100Desc: "Earn 100 Swiss Money in Rome in a single run",
  AchievementRome500: "Constantine the Great",
  AchievementRome500Desc: "Earn 500 Swiss Money in Rome in a single run",
  AchievementRome1000: "Caesar Augustus",
  AchievementRome1000Desc: "Earn 1000 Swiss Money in Rome in a single run",
  AchievementHamburg100: "Deutschland",
  AchievementHamburg100Desc: "Earn 100 Swiss Money in Hamburg in a single run",
  AchievementHamburg500: "Vaterland",
  AchievementHamburg500Desc: "Earn 500 Swiss Money in Hamburg in a single run",
  AchievementHamburg1000: "Graf Zeppelin",
  AchievementHamburg1000Desc:
    "Earn 1000 Swiss Money in Hamburg in a single run",
  AchievementToulouse100: "Jetliner A310",
  AchievementToulouse100Desc:
    "Earn 100 Swiss Money in Toulouse in a single run",
  AchievementToulouse500: "Jetliner A330",
  AchievementToulouse500Desc:
    "Earn 500 Swiss Money in Toulouse in a single run",
  AchievementToulouse1000: "Jetliner A380",
  AchievementToulouse1000Desc:
    "Earn 1000 Swiss Money in Toulouse in a single run",
  AchievementHongKong100: "Hobbyist Trader",
  AchievementHongKong100Desc:
    "Earn 100 Swiss Money in Hong Kong in a single run",
  AchievementHongKong500: "Professional Broker",
  AchievementHongKong500Desc:
    "Earn 500 Swiss Money in Hong Kong in a single run",
  AchievementHongKong1000: "Hedge Fund Manager",
  AchievementHongKong1000Desc:
    "Earn 1000 Swiss Money in Hong Kong in a single run",
  AchievementStPetersburg100: "The Grand Duke",
  AchievementStPetersburg100Desc:
    "Earn 100 Swiss Money in St. Petersburg in a single run",
  AchievementStPetersburg500: "The Tsesarevich",
  AchievementStPetersburg500Desc:
    "Earn 500 Swiss Money in St. Petersburg in a single run",
  AchievementStPetersburg1000: "The Tsar of All Russia",
  AchievementStPetersburg1000Desc:
    "Earn 1000 Swiss Money in St. Petersburg in a single run",
  AchievementOsaka100: "Danshaku",
  AchievementOsaka100Desc: "Earn 100 Swiss Money in Osaka in a single run",
  AchievementOsaka500: "Hakushaku",
  AchievementOsaka500Desc: "Earn 500 Swiss Money in Osaka in a single run",
  AchievementOsaka1000: "Kōshaku",
  AchievementOsaka1000Desc: "Earn 1000 Swiss Money in Osaka in a single run",
  SteamAutoCloudBackup: "Steam Cloud Auto Backup",
  SteamAutoCloudBackupFailed: "Steam Cloud Auto Backup Failed: %{error}",
  SteamManualBackup: "Force Steam Cloud Backup",
  UILoading: "Loading...",
  UserAuthenticated: "You are authenticated",
  BuildingResourceBreakdown: "Idle Amount Breakdown",
  SortByDeficit: "Deficit",
  SortByRunOut: "Run Out",
  SocialNetworkInc: "Social Network Inc",
  SocialNetwork: "Social Network",
  DatabaseCompany: "Database Company",
  Database: "Database",
  SatelinkInc: "Satelink Inc",
  GameStationInc: "GameStation Inc",
  AirShuttleInc: "Air Shuttle Inc",
  AircraftCarrierFactory: "Aircraft Carrier Factory",
  AircraftCarrier: "Aircraft Carrier",
  MapExclusive: "Map Exclusive",
  ElectricCar: "Nikola Tesla",
  ElectricCarDesc:
    "Car factories use batteries instead of petrol and only require 50% of the amount",
  HongKongBonusV2:
    "<li>Unique market pricing algorithm - prices and stock rating follow normal distribution (bell curve)</li><li>Market updates and trade quota resets are twice as frequent (every hour)</li><li>Research can be unlocked via traded resources</li><li>Unique building: Kung-Fu Dojo</li><li>Unique building: Tai-Chi Dojo</li><li>50% increase in max numbers of active player trades allowed</li><li>Start with 1 more auto sell concurrency</li><li>Unique policy: International Export Trade</li><li>Unique policy: Pearl of the Orient</li><li>Wholesale Center only needs 4 resources to unlock</li><li>Start with 100M Cash</li>",
  TaiChi10xCultureDescV2:
    "Free Kung-fu and Tai-chi transportation. Movie studios have 2x capacity but uses 50% more power",
  SettingsFullScreen: "Full Screen",
  SettingsFullScreenDesc:
    "Run the game in fullscreen mode. Only available for Steam version",
  LeaderboardByAllPrestigeCurrency: "All Time Swiss Money Earned",
  LeaderboardByCash: "Current Cash At Hand",
  LeaderboardTotalValuation: "Total Valuation",
  LeaderboardDescV2: "See the where the top players are",
  LastUpdatedAt: "Last Updated At",
  DetroitBonusV3:
    "<li>Engine factories are unlocked</li><li>Engine factories have 2x productivity</li><li>Car factories have 2x capacity</li><li>Car factories use gas instead of petrol</li><li>Free car transportation</li><li>Nikola Tesla policy is free</li><li>Train factories have 2x capacity</li>",
  SaveAndExit: "Save and Exit Game",
  SaveAndExitDesc:
    "Save and exit game. This is only available on Steam version and does the same as the close button on the window bar",
  AutoSellResourceWarningShortLabel: "💡Auto Sell",
  AutoSellResourceWarningDesc:
    "You are auto selling this resource, the amount stored in Trade Center cannot be used here",
  PlayerTradeLocalPrice: "Local Price: %{price}",
  ChatForceScroll: "Force Scroll",
  ChatForceScrollDesc:
    "If force scroll is on, the chat will scroll whenever there's a new message. Otherwise it will only scroll when you are already at the bottom",
  ResourceExplorer2: "Resource Explorer 2.0",
  ConstructionCancel: "Cancel",
  PolicyBlueprint: "Blueprint",
  PolicyBlueprintDesc:
    "Construction of a building will not automatically start - it has to be started manually (FREE POLICY)",
  HighlightUnderConstruction: "...that haven't been constructed",
  HighlightUnderLevel10: "...that are under level 10",
  HighlightUnderLevel20: "...that are under level 20",
  HighlightUnderLevel30: "...that are under level 30",
  Logout: "You Are Logged Out",
  ConstructionStatusQueueingV2: "Queueing",
  ConstructionStatusPausedV2: "Paused",
  ConstructionStatusBuildingV2: "Building",
  ConstructionStatusUnpaidV2: "Unpaid",
  ConstructionStatus: "Construction Status",
  ConstructionStart: "Start",
  CostFree: "Free",
  PlaceBlueprint: "Place a building blueprint is free",
  PlayerTradePriceNotValidV2: "Trade price must be between %{min} and %{max}",
  MarketNews: "Market News",
  MarketNewsApplyToYou: "Only you",
  MarketNewsApplyToGlobal: "Global",
  MarketNewsHighlightAffected: "🔍 Highlight",
  MarketNewsFilterInput: "All %{res} input ",
  MarketNewsFilterOutput: "All %{res} output ",
  MarketNewsFilterBoth: "All %{res} input and output ",
  MarketNewsIncrease: "increased by %{percent}",
  MarketNewsDecrease: "decreased by %{percent}",
  MarketNewsBuilding: "This building is affected by %{num} news",
  StockholmBonusV2:
    "<li>Unique building: music producer</li><li>Logging camps have 2x output</li><li>Paper mills are unlocked</li><li>Circuit foundries have 2x productivity</li><li>Science Literature policy is free</li>",
  FreeOilTransportV2: "Electric Oil Transport",
  Tutorial4P1:
    "Resource transportation costs fuel. There are several fuel types and now you are using <em>petrol⛽</em> as fuel. You have an <em>oil refinery</em> that transports oil from the oil well and produces petrol.<br><br>The tiny moving <em>dots</em> represent the real-time movement of resources. You should optimize your building locations to minimize the distance of travel.<br><br><em>Upgrading</em> your buildings will increase their output, but will also increase their power usage and input required.",
  Tutorial4P2:
    "You can change your fuel type in the <em>logistics department🚦</em> - on this map, you can also use <em>natural gas</em> as fuel.<br><br>The logistics department also shows your transportation routes that burns most fuel - you'll want to keep an eye on it.<br><br>Remember to <em>make sure your fuel production is above consumption</em> otherwise your production will halt when you run out of fuel.<br><br>If that happens, don't worry, you can buy some emergency fuel from the trade center or from other players",
  Tutorial5P2:
    "<em>The statistics bureau📊</em> provides a good overview of your production. You can see a detailed breakdown of your resource input and output.<br><br>There are also lots of useful charts📈 - you'll want to refer to them when you balance your production.<br></br>Your <em>cash💰, power surplus⚡ and fuel surplus⛽</em> numbers are also shown on the top left corner - if any of them turns red, you should investigate what's going on.",
  MusicProducer: "Music Producer",
  PlasticFiber: "Plastic Fiber",
  PlasticFiberDesc: "Fiber factories use 50% more plastics but 50% less glass",
  NewsEffectx2: "Press Conference",
  NewsEffectx2Desc:
    "The effect of market news doubles, both positive and negative",
  SellRefundPercentage: "Sell/Downgrade Refund",
  SellRefundPercentageDesc:
    "If you sell or downgrade a building, this is the percentage of cash and resources you are refunded",
  SellBuildingDescV2:
    "Selling a building will refund you %{percent} of your investment and %{percent} of the resources will be transported to Trade Center",
  BuilderMoveSpeed: "Builder Move Speed",
  BuilderMoveSpeedDesc: "The speed that builders move to construct buildings",
  EBookInc: "eBook Inc",
  ResourceBooster: "Resource Booster",
  BuildWarningTitle: "Building Might Not Work",
  BuildWarningTitleDesc: "%{reason}. Are you sure to build on this tile?",
  BuildWarningBuildAnyway: "Build Anyway",
  ResourceBoosterNotWorking:
    "⛔ Resource boosters only work next to deposit mines",
  ResourceBoosterBuildings: "Buildings Being Boosted",
  BuildingResourceConversion: "%{resource} Conversion",
  AllTimeSwissMoneyEarned: "All time Swiss Money earned: %{number}",
  BuildingUpgradeCostDivider: "Building Upgrade Cost Divider",
  AchievementSoftwareGiant: "Software Giant",
  AchievementSoftwareGiantDesc:
    "Build a level 10 Software Company, level 10 Operating System Inc, level 10 Database Company and level 10 Web Browser on the same map",
  AchievementSpaceRace: "Space Race",
  AchievementSpaceRaceDesc:
    "Build a level 10 Rocket Factory, level 10 Satellite Factory, level 10 Spaceship Factory and level 10 Space Station Factory on the same map",
  AchievementToTheMoon: "To The Moon",
  AchievementToTheMoonDesc:
    "Build a level 40 Bitcoin Farm and level 40 Dogecoin Farm. Own 1B Bitcoin and 1B Dogecoin",
  ItsAllGreen: "It's All Green",
  ItsAllGreenDesc: "Have 50 production lines and no production deficit at all",
  DeepInRed: "Deep In Red",
  DeepInRedDesc: "Have 50 production lines that has production deficit",
  UseScientificNotation: "Use Scientific Notation",
  UseScientificNotationDesc:
    "Use scientific notation (e notation) for numbers larger than 999.9T",
  LogoutDescV2:
    "You have logged in on another device, this device is logged out. You can log back in but the other device will be logged out",
  LogBackIn: "Log Back In",
  PlayerTradeNowAllowedV2:
    "Player trades are not available within %{hour} hours of restoring/importing a save",
  ServerDisconnected:
    "You are disconnected from the server, please check your internet connection and restart the game",
  BuildingUpgradeCostDividerDescV2:
    "Divide building upgrade cost by this divider",
  ResourceBoosterDesc: "Boost the output of adjacent mines",
  BlockUserChatTitle: "Block %{user}",
  BlockUserChatAction: "Block",
  BlockUserChatDesc:
    "The block will be in effect during this game session and you cannot undo this unless you restart the game",
  ChangeNameCooldown: "You can only change your name once every %{hour} hours",
  AtomicBombFactory: "Atomic Bomb Factory",
  AtomicBomb: "Atomic Bomb",
  DynamiteFactory: "Dynamite Factory",
  Dynamite: "Dynamite",
  NuclearMissileFactory: "Nuclear Missile Factory",
  NuclearMissile: "Nuclear Missile",
  LiquidPropellantFactory: "Liquid Propellant Factory",
  GasPropellantFactory: "Gas Propellant Factory",
  Propellant: "Propellant",
  ProjectV2: "Project V-2",
  ICBMFactory: "ICBM Factory",
  ICBM: "ICBM",
  RadarFactory: "Radar Factory",
  Radar: "Radar",
  SpaceForceCommand: "Space Force Command",
  SpaceForce: "Space Force",
  SteamAutoCloudBackupDescV2:
    "Your latest progress is saved to Steam Cloud and synced across devices. The game also backs up your save every 10 minutes automatically to Steam Cloud. You can force a backup at any time",
  SpaceColony: "Space Colony",
  SpaceColonyInc: "Space Colony",
  ProjectVostok: "Project Vostok",
  AdjacentBonusSquare: "Adjacent Bonus Square",
  AdjacentBonusSquareDesc:
    "Adjacent bonus is 50% more effective, but tile modifiers scale from -15% to +15%",
  ResourceBoosterSquare: "Resource Booster Square",
  ResourceBoosterSquareDesc:
    "Resource boosters provide 25% more boost but their science input and power usage also increase by 25%",
  SteelMillx2: "Steel Furnace Modernization",
  SteelMillx2Desc:
    "Steel mills and stainless steel plants have 2x capacity but uses 2x power",
  FuelDynamite: "Fuel Dynamite",
  FuelDynamiteDesc: "Dynamite factories use your current fuel instead of oil",
  StPetersburgBonusV2:
    "<li>Uranium mines have 2x output</li><li>Uranium enrichment plants have 2x capacity</li><li>Uranium transportation costs 50% less fuel</li><li>Free gun transportation</li><li>Project Vostok has 2x capacity</li>",
  ToulouseBonusV2:
    "<li>Titanium mines have 2x output</li><li>Uranium enrichment plants have 2x productivity</li><li>Jet engine factories have 2x capacity</li><li>Aircraft factories have 2x productivity</li><li>Rocket factories have 2x capacity</li>",
  BuildingPermitsNeededDesc:
    "This building is not working because you don't have enough building permits",
  BuildingPermitsNeeded: "Building Permits Needed",
  BuyMissingPermits: "Buy Missing Permits",
  GPUIsBusy: "Your GPU is Busy",
  GPUIsBusyDesc:
    "Your operating system has paused the game's graphics because the GPU is busy with other tasks. You can reload the game to resume. If it doesn't work, try restarting the game",
  SaveAndReloadGame: "Save And Reload Game",
  ResearchLabCultureInput: "The Renaissance",
  ResearchLabCultureInputDesc:
    "Research Lab has 2x capacity but takes culture as the extra input",
  GasPumpx2Output: "High Pressure Gas Pump",
  GasPumpx2OutputDesc: "Natural gas pumps have 2x output but use 2x power",
  LeaderboardValuationPerHour: "Total Valuation Per Hour",
  LeaderboardValuationPerHourPerSwiss: "Total Valuation Per Hour Per Swiss",
  LeaderboardValuationPerHourNewPlayers:
    "Total Valuation Per Hour (< 1000 Swiss)",
  LeaderboardValuationPerBuilding: "Building Valuation Per Building",
  BuildingCustomColor: "Building Color",
  BuildingCustomColorReset: "Reset",
  Vancouver: "Vancouver",
  VancouverBonus:
    "<li>Every 4 different types of buildings give 1 free building permit</li><li>Unique policy: Production Diversification</li><li>Unique building: Maple Syrup Factory</li><li>Free maple syrup transport</li><li>Unique fuel type: Maple Syrup</li><li>2x player trade quota when trading Uranium and Enriched Uranium</li><li>Unique free policy: Syrup Plastic</li><li>Toy factories have 2x productivity</li><li>Game studios have 2x capacity</li>",
  MapExtraPermitDesc:
    "You get %{number} free building permits from the map's unique bonus",
  OsloBonusV3:
    "<li>Oil refineries are unlocked</li><li>Oil refineries have 2x capacity</li><li>Electric oil transport policy is free</li><li>Gas processing plants have 2x capacity</li><li>Free level 4 wind turbine x1</li><li>Free level 8 oil well x1</li><li>Free level 2 oil refinery x1</li><li>Free level 2 natural gas pump x1</li>",
  ResourceBoosterPercentageV2:
    "💡 This amount includes %{percent} boost from adjacent resource boosters",
  MapleSyrup: "Maple Syrup",
  MapleSyrupFactory: "Maple Syrup Factory",
  SyrupPlastic: "Syrup Plastic",
  SyrupPlasticDesc: "All buildings that input plastic use maple syrup instead",
  ResourceBoosterSupplyChain: "Supply Chain Booster",
  ResourceBoosterSupplyChainDesc:
    "Resource boosters use 2x power and science, but for each working mine a resource booster is boosting, it also provides capacity boost to adjacent factories that consume the mine's output (the factory should only consume deposits)",
  ProductionDiversification: "Production Diversification",
  ProductionDiversificationDesc:
    "Each different type of building gives 1% extra capacity to all buildings",
  ExtraPolicyPointsDescV2:
    "Policy center has 2x policy points conversion capacity",
  PowerRequired: "Power Required",
  AchievementVancouver100: "Sap Seller",
  AchievementVancouver100Desc:
    "Earn 100 Swiss Money in Vancouver in a single run",
  AchievementVancouver500: "Syrup Savant",
  AchievementVancouver500Desc:
    "Earn 500 Swiss Money in Vancouver in a single run",
  AchievementVancouver1000: "Canuck Conqueror",
  AchievementVancouver1000Desc:
    "Earn 1000 Swiss Money in Vancouver in a single run",
  BarbariansAtTheGate: "Barbarians At The Gate",
  BarbariansAtTheGateDesc:
    "Use 1 trillion worth of player trade quota between market updates",
  DiversifiedProductions: "Diversified Productions",
  DiversifiedProductionsDesc:
    "Build 100 different types of buildings on a single map",
  RealEstateTycoon: "Real Estate Tycoon",
  RealEstateTycoonDesc: "Have 400 buildings on a single map",
  ResourceExplorer2DescV2:
    "Resource explorers produce 2x output but use 2x power. Resource explorers can be boosted by resource boosters if Supply Chain Booster policy is active and the booster has an adjacent mine of the same output",
  NoTileModifier: "Earth Is Flat",
  NoTileModifierDesc:
    "All tile modifiers are zero. This policy will deactivate Nature's Power and Tile Modifier Plus policies",
  DoubleTileModifierDescV2:
    "All tile modifiers' effect x2 - both positive and negative. This policy will deactivate Earth Is Flat policy",
  TileModifierOutputOnlyDescV2:
    "Tile modifiers only affect output instead of both input and output but are only 50% effective. This policy will deactivate Earth Is Flat policy",
  QuickLinks: "Quick Links",
  GetHelp: "Get Help",
  GetHelpBeginnerGuides: "Beginner's Guide",
  GetHelpSteamGuides: "Other Steam Guides",
  GetHelpInGameChat: "Ask In-Game Chat",
  GetHelpDiscord: "Join Our Discord Server",
  GetHelpWiki: "Community Wiki",
  SelectATile: "Select a Tile",
  PledgeAmount: "Pledge %{amount}",
  PledgeValue: "Value $%{amount}",
  TotalPledgedValue: "Total Pledged Value",
  TotalPledgedValueDesc:
    "Your first pledge counts towards the crowdfunding goal. Subsequent pledges increase total pledged value but do not count towards the goal",
  ReturnOnPledge: "Return On Pledge",
  CrowdfundingEndIn: "End in %{time}",
  ClaimCrowdfundingReward: "Claim Reward %{amount}",
  PledgeSuccessful: "You have pledged %{amount} to this crowdfunding",
  CrowdfundingClaimSuccessful: "You have claimed %{amount} cash",
  CrowdfundingAlreadyPledged: "You've Already Pledged",
  CrowdfundingAlreadyPledgedDesc:
    "You can pledge more resources, which will increase your total pledged value (and potential return), but won't count towards crowdfunding goal",
  WholesaleCenterProducingOnly: "Wholesale Partners",
  WholesaleCenterProducingOnlyDesc:
    "Wholesale center orders only contain resources that are currently being produced (you also need to be producing the number of required resources to unlock wholesale center)",
  SoftwareCompiler: "Software Compiler",
  SearchEngine: "Search Engine",
  SearchEngineCompany: "Search Engine Company",
  Navy: "Navy",
  NavyCommand: "Navy Command",
  Battleship: "Battleship",
  BattleshipFactory: "Battleship Factory",
  ResourceMovementHide: "Always Hide",
  ResourceMovementShow: "Always Show",
  ResourceMovementHighlight: "On Highlight",
  ResourceMovementLine: "Line Only",
  ResourceMovement: "Resource Movement",
  ResourceMovementDesc:
    "You can choose when to show the resource movement (dots). Hiding it can improvement performance",
  CrowdfundingCashInWarning:
    "You have pending crowdfunding pledges - starting in a new city will forfeit them",
  ResourceBoosterBannerDescV2:
    "💡 You currently have %{number} resource boosters - the science input of each is scaled to the number of resource boosters you currently have",
  CrowdfundingId: "Crowdfunding %{id}",
  PatchNotes: "Patch Notes",
  PatchNotesDesc: "Read what's new in this update",
  PanelPositionLeft: "Left (Docked)",
  PanelPositionLeftFloat: "Left (Float)",
  PanelPositionRight: "Right (Docked)",
  PanelPositionRightFloat: "Right (Float)",
  PanelPositionAuto: "Auto",
  TimePlayed: "Time Played",
  ValuationPerHour: "Valuation Per Hour",
  HighPowerPriority: "High Power Priority",
  HighPowerPriorityDesc:
    "Switching this on will make the building draw power before other buildings",
  IndustryZone: "Industry Zone",
  IndustryZoneDesc:
    "Combine adjacent buildings that forms a supply chain and save building permits",
  IndustryZoneMaxBuildingLevel: "Max Building Level",
  IndustryZoneNotWorkingDesc:
    "All of its adjacent buildings should form a supply chain and are not part of other industry zones",
  IndustryZoneNoAdjacentBonus:
    "This building is part of an industry zone and does not have adjacent bonus",
  PlayerTradeAutoClaim: "Automatically claim filled trades",
  MusifyInc: "Musify Inc",
  WebflixInc: "Webflix Inc",
  CloudStreaming: "Cloud Steaming",
  GameCloudInc: "GameCloud Inc",
  SuperComputerLab: "Super Computer Lab",
  SuperComputer: "Super Computer",
  SkyNetInc: "SkyNet Inc",
  SkyNet: "SkyNet",
  RobocarFactory: "Robocar Factory",
  Robocar: "Robocar",
  WarehouseBuildingPermitSave: "Warehouse Permit Act",
  WarehouseBuildingPermitSaveDesc:
    "Every two warehouses provide one free building permit",
  PolicySearchPlaceholder: "Type a policy name to search",
  SwissUpgrade: "Swiss Upgrade",
  SwissUpgradeDesc:
    "Swiss upgrades are permanent and will carry over if you start in a new city",
  SwissBoost: "Swiss Boost",
  SwissBoostDesc:
    "Swiss boosts only affect your current run - and will reset if you start in a new city",
  ProductionMultipliers: "Production Multipliers",
  MultiplierMapUniqueBonus: "Map Unique Bonus",
  MultiplierSwissUpgrade: "Swiss Upgrade (Permanent)",
  MultiplierSwissBoost: "Swiss Boost (This Run)",
  SwissBoostCostDivider: "Swiss Boost Cost Divider",
  SwissBoostCostDividerDesc:
    "Divide Swiss boost cost by this divider - only applies to multiplier/divider upgrades",
  AirForceCommand: "Air Force Command",
  AirForce: "Air Force",
  StealthFighterFactory: "Stealth Fighter Factory",
  StealthFighter: "Stealth Fighter",
  ArmyCommand: "Army Command",
  Army: "Army",
  GreenPeacekeeper: "Green Peacekeeper",
  GreenPeacekeeperDesc:
    "Make army, navy, air force or space force with only renewable power plants (wind/solar)",
  DotComTycoon: "DotCom Tycoon",
  DotComTycoonDesc:
    "Build a level 10 Social Network Inc, level 10 Search Engine Company, level 10 SkyNet Inc and level 10 Musify Inc on the same map",
  ConstructionNotResearched: "Not Researched",
  OfflineEarningDescV2:
    "Offline earning depends on your current research, production and auto sell",
  HighSpeedWarehouse: "High Speed Warehouse",
  HighSpeedWarehouseDesc:
    "Warehouses have 2x capacity and 50% faster inward and outward transport speed, but use 2x power",
  IndustryZoneMultiplierDesc: "Industry Zone Bonus",
  IndustryZoneMultiplierSwissBoost: "Industry Zone Capacity Booster",
  EarningPerMinuteV2: "Offline Earning Rate",
  OfflineResearchPoint: "Offline Research Point",
  WholesaleCenterOrderFasterV2: "Bigger Faster Wholesale",
  OfflineResearchSwissBoost: "Offline Research",
  OfflineResearchSwissBoostDesc:
    "Research points are generated while you are offline (according to your Research Lab level, Science in your warehouse and offline earning time)",
  SanJose: "San Jose",
  SanJoseBonus:
    "<li>Unique building: chip manufacturer</li><li>Unique building: FaceApp Inc</li><li>Unique building: Bitcoin Miner</li><li>All buildings that consume silicon have max tile modifier</li><li>Solar panels generate 2x power</li><li>Silicon mines have 2x output</li>",
  RotterdamBonusV2:
    "<li>Steel Mills have 2x capacity</li><li>Stainless Steel Plants have 2x capacity</li><li>Free iron transportation</li><li>Steel transportation costs 50% less fuel</li><li>Start with 2x auto sell capacity</li><li>Earth Is Flat policy is free</li>",
  ChipManufacturer: "Chip Manufacturer",
  SnapTokInc: "SnapTok Inc",
  FaceAppInc: "FaceApp Inc",
  BitcoinMiner: "Bitcoin Miner",
  GalvanicBatteryFactory: "Galvanic Battery Factory",
  BaseProductionMultiplier: "Base Production",
  ShowBreakdown: "Show Breakdown",
  HideBreakdown: "Hide Breakdown",
  IndustryZoneMultiplierSwissBoostDescV2:
    "Each tier of production chain inside an industry zone provides this capacity boost to all the buildings in the same zone",
  IndustryZoneBuildingPermitDesc:
    "If an industry zone has N tiers of productions, it will provide N-2 building permits for free",
  CrowdfundingBackersReturn: "Backers: %{backers}, Current Return: %{return}",
  CrowdfundingBackersNeeded: "%{backers} More Backer(s)",
  CrowdfundingReturnBonus: "+%{return} Return",
  ReturnOnPledgeDescV2:
    "Your total return equals to total pledged value multiplied by return rates from all resources. More backers of a resource will improve its return",
  PlayerTradeQuotaDescV2:
    "💡 Quota is the amount of the resource you can trade. The monetary value equals to %{percent} of your market cap and it resets when the market updates. The more your trade's price deviates from your trade center price, the more quota you need",
  AchievementSanJose100: "Venture Hobbyist",
  AchievementSanJose100Desc: "Earn 100 Swiss Money in San Jose in a single run",
  AchievementSanJose500: "Venture Enthusiast",
  AchievementSanJose500Desc: "Earn 500 Swiss Money in San Jose in a single run",
  AchievementSanJose1000: "Venture Capitalist",
  AchievementSanJose1000Desc:
    "Earn 1000 Swiss Money in San Jose in a single run",
  AchievementCrowdfundingTycoon: "Crowdfunding Tycoon",
  AchievementCrowdfundingTycoonDesc:
    "Pledge 1Qa worth of resources in a single crowdfunding",
  AchievementCashIsKing: "Cash Is King",
  AchievementCashIsKingDesc: "Have 1Qa cash at hand in a single run",
  AchievementPowerTycoon: "Power Tycoon",
  AchievementPowerTycoonDesc: "Generate 1GW power in a single run",
  PlayerTradeFilteringNResources: "Filtering %{n} Resource(s)",
  PlayerTradeFilterResources: "Filter Resources",
  PlayerTradeFilterClear: "Clear Filters",
  ResourceExplorerAll: "Explore All Resources",
  ResourceExplorerAllDesc:
    "Resource explorers can produce all resources, including the ones that are not on the map (this DOES NOT unlock the relevant technologies)",
  ShowResourceInTopBar: "Show In Top Bar",
  LeaderboardOptOutDescV2:
    "You will no longer appear in the leaderboard. This will also disable player trade. PLEASE NOTE: if you want to enable leaderboard later, your data needs to be reset",
  PolicyPointNoCopperDesc:
    "💡 This map doesn't have copper deposits, you can activate Al Circuit policy to unlock further technologies",
  Pumpkin: "Pumpkin",
  PumpkinBattery: "Pumpkin Battery",
  PumpkinBatteryDesc:
    "All buildings that consume battery use pumpkin instead (FREE POLICY)",
  PumpkinSteel: "Pumpkin Steel",
  PumpkinSteelDesc:
    "All buildings that consume steel use pumpkin instead (FREE POLICY)",
  RequireExpansionPack2: "Expansion Pack 2",
  ExpansionPack2: "Expansion Pack 2",
  RequireExpansionPack2Desc: "This is only available for Expansion Pack 2",
  Reindeer: "Reindeer",
  ReindeerSilicon: "Reindeer Silicon",
  ReindeerSiliconDesc:
    "All buildings that consume silicon use reindeer instead (FREE POLICY)",
  ReindeerAluminum: "Reindeer Aluminum",
  ReindeerAluminumDesc:
    "All buildings that consume aluminum use reindeer instead (FREE POLICY)",
  SantaClauseIsComing: "Santa Clause is Coming",
  SantaClauseIsComingDesc:
    "Santa factories consume reindeer and toy and produce santa, science and culture. Santa factories have max tile modifier. Toy factories produce reindeer in addition to toy (FREE POLICY)",
  MetaRebranding: "Meta Rebranding",
  MetaRebrandingDesc:
    "Social Network Inc is renamed to Meta Inc and consumes internet, game, super computer, bitcoin and dogecoin instead",
  MetaInc: "Meta Inc",
  ImportSave: "Import Save",
  ExportSave: "Export Save",
  ClearMyTrades: "Clear My Trades",
  SaveVersionTooNew:
    "Your save is from %{saveVersion} but your game is %{gameVersion}. Please update your game first",
  LeaderboardByFlag: "Tabluation By Player Flag",
  LeaderboardByMap: "Tabluation By Map",
  LeaderboardByFlagPlayerFlag: "Flag",
  LeaderboardByFlagPayerCount: "#",
  LeaderboardByFlagPayerValuationPerHour: "V/H",
  LeaderboardByFlagPayerSwissMoney: "Swiss",
  PlayerTradePriceFilter: "Price Filter",
  PlayerTradeFilterBetterThanMarket: "Better than Market",
  PlayerTradeFilterAll: "All",
  PlayerTradeFilterBestPrice: "Best Price",
  CrowdfundingTotalPledgdeValueTooLarge:
    "Your Total Pledged Value for a crowdfunding cannot exceed your current Market Cap",
  BuildingSourceAuto: "Auto Source",
  BuildingSourceManual: "🔍 Manual Source",
  BuildingSourceReset: "Reset",
  BuildingSourceSelecting: "Tap On Map...",
  BuildingSourceSetOverride: "Override",
  BuildingSourceFallback: "Manual Source Fallback",
  BuildingSourceFallbackDesc:
    "How should the building transport its input if the manual source doesn't have enough? Skip - do not transport; drain - transport what's left; new - use auto source to find a new source",
  BuildingSourceFallbackSkip: "Skip",
  BuildingSourceFallbackDrain: "Drain",
  BuildingSourceFallbackAuto: "New",
  BuildingSourceFallbackMarker: "(Fallback)",
  BuildingSourceFallbackMarkerDesc:
    "The manual source doesn't have enough resource, fallback strategy is active",
  BuildingSourceInvalid:
    "Your selected source is invalid, please select a valid tile",
  RandomIsland: "Random Island",
  RandomIslandBonus:
    "<li>The map is randomized every time you start</li><li>Map size, grid type, resource deposits and unique bonuses are all randomly rolled</li><li>There is a 5-minute cool down - the reroll only happens minimum 5 minutes apart</li>",
  RandomIslandBonusDesc:
    "The unique bonus on Random Island is rerolled every time you start on the map",
  RandomIslandBonusCapacity: "%{building} has %{multiplier}x capacity",
  RandomIslandBonusProductivity: "%{building} has %{multiplier}x productivity",
  RandomIslandBonusResources: "Resource deposits on this map: %{deposits}",
  ValuationPerActiveMinute: "Valuation Per Active Minute",
  Perth: "Perth",
  PerthBonus:
    "<li>Building spinners rotate clockwise, which is opposite to other cities</li><li>Unique deposit: Geothermal vent</li><li>Unique building: Geothermal Power Plant</li><li>Unique policies: Adjacent Explorer (FREE), Factory Mining (FREE)</li>",
  GV: "Geothermal Vent",
  GeothermalPowerPlant: "Geothermal Power Plant",
  AdjacentExplorer: "Adjacent Explorer",
  AdjacentExplorerDesc:
    "A resource explorer produce 2x output if it's adjacent to the resource it's producing (FREE POLICY)",
  FactoryMining: "Factory Mining",
  FactoryMiningDesc:
    "A factory can mine the deposit directly from the tile if it consumes the same deposit (FREE POLICY)",
  FactoryMiningBanner:
    "This building is mining %{resource} directly from this tile",
  WarehouseSourceWeight: "Weight: %{weight}",
};




